version: "3.9"

services:

  api:
    build: .
    depends_on:
      - postgres
      - redis
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    command: >
      sh -c "
      until pg_isready -h postgres -p 5432; do
        echo 'Waiting for Postgres...';
        sleep 2;
      done;
      npx prisma migrate deploy;
      node src/server.js
      "

  worker:
    build: .
    depends_on:
      - postgres
      - redis
    restart: always
    env_file:
      - .env
    command: >
      sh -c "
      until pg_isready -h postgres -p 5432; do
        echo 'Waiting for Postgres...';
        sleep 2;
      done;
      node src/workers/audit.workers.js
      "

  redis:
    image: redis:7
    restart: always
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:15
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  redis_data: